project_name: ntgtag
before:
  hooks:
  - go mod tidy
  - go generate ./...
builds:
- env:
  - CGO_ENABLED=0
  goos:
  - linux
  - windows
  - darwin
  goarch:
  - amd64
  - arm64
archives:
- replacements:
    amd64: x86_64
  name_template: "{{ .ProjectName }}_{{ .Os }}_{{ .Arch }}"
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: 'current'
changelog:
  sort: asc
  filters:
    exclude:
    - '^docs:'
    - '^test:'
